package ru.yusdm.technics.jooq

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.CommandLineRunner
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import ru.yusdm.technics.jooq.jooq.autogenerated.tables.pojos.JpjCity
import ru.yusdm.technics.jooq.jooq.autogenerated.tables.pojos.JpjCountry

@SpringBootApplication
class Application : CommandLineRunner {

    @Autowired
    lateinit var service: ServiceDefault

    override fun run(vararg args: String) {
        val country = JpjCountry("Country_1111", 1)
        val country2 = JpjCountry("Country_2222", 1)
        service.insertCountry(country)
        service.insertCountry(country2)

        val myCountry = MyCountry("Country_3", 20)
        val countryId = service.insertCountry2(myCountry)

        val city = JpjCity( "street", "mainStreet", countryId)
        val city2 = JpjCity( "street_2", "mainStreet_2", countryId)
        service.insertCity(city)
        service.insertCity(city2)

       // service.getCitiesByCountryId(countryId).forEach { println(it.id.toString() + " " + it.name) }
        service.getCitiesByCountryId2(countryId).forEach { println(it.id.toString() + " " + it.name) }
    }

}

fun main(vararg args: String){
    SpringApplication.run(Application::class.java, *args)
}