spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/javaquiz
    username: "test"
    driver-class-name: "org.postgresql.Driver"
    password: "111"