server:
  port: 9093
spring:
  profiles:
    active: postgresql
  jpa:
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG