/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.technics.jooq.jooq.autogenerated.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JpjBook implements Serializable {

    private static final long serialVersionUID = -1722613681;

    private final Long   id;
    private final String name;

    public JpjBook(JpjBook value) {
        this.id = value.id;
        this.name = value.name;
    }

    public JpjBook(
        Long   id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JpjBook (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
