/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.technics.jooq.jooq.autogenerated.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JpjBookDescription implements Serializable {

    private static final long serialVersionUID = -1001946125;

    private final String description;
    private final Long   bookId;

    public JpjBookDescription(JpjBookDescription value) {
        this.description = value.description;
        this.bookId = value.bookId;
    }

    public JpjBookDescription(
        String description,
        Long   bookId
    ) {
        this.description = description;
        this.bookId = bookId;
    }

    @Size(max = 255)
    public String getDescription() {
        return this.description;
    }

    @NotNull
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JpjBookDescription (");

        sb.append(description);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
