/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.technics.jooq.jooq.autogenerated;


import ru.yusdm.technics.jooq.jooq.autogenerated.tables.JBook;
import ru.yusdm.technics.jooq.jooq.autogenerated.tables.JBookDescription;
import ru.yusdm.technics.jooq.jooq.autogenerated.tables.JCity;
import ru.yusdm.technics.jooq.jooq.autogenerated.tables.JCountry;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.book</code>.
     */
    public static final JBook BOOK = JBook.BOOK;

    /**
     * The table <code>public.book_description</code>.
     */
    public static final JBookDescription BOOK_DESCRIPTION = JBookDescription.BOOK_DESCRIPTION;

    /**
     * The table <code>public.city</code>.
     */
    public static final JCity CITY = JCity.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public static final JCountry COUNTRY = JCountry.COUNTRY;
}
