package ru.yusdm.technics.f

import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import ru.yusdm.technics.f.jooq.autogenerated.tables.pojos.JpjCity
import ru.yusdm.technics.f.jooq.autogenerated.tables.pojos.JpjCountry

@Service
@Transactional
class ServiceDefault(private val repo: RepoDefault) {

    fun insertCountry(country: JpjCountry) {
        repo.insertCountry(country)
    }

    fun insertCountry2(country: MyCountry) : Long {
        return repo.insertCountry2(country)
    }

    fun insertCity(city: JpjCity) {
        repo.insertCity(city)
    }

    fun getCitiesByCountryId(countryId: Long): List<JpjCity> {
        return repo.getCitiesByCountryId(countryId)
    }

    fun getCitiesByCountryId2(countryId: Long): List<JpjCity> {
        return repo.getCitiesByCountryId2(countryId)
    }

}